# Generated by Django 6.1.1 on 2026-09-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ['destination', 'order']},
        ),
        migrations.AddField(
            model_name='highlight',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='highlights/videos/'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
