# Generated by Django 6.1.1 on 2026-09-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('van', 'Van'), ('suv', 'SUV'), ('minivan', 'Mini Van')], default='car', max_length=30)),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('short_description', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('passenger_capacity', models.PositiveIntegerField(default=3)),
                ('luggage_capacity', models.PositiveIntegerField(default=2)),
                ('air_conditioned', models.BooleanField(default=True)),
                ('comfortable', models.BooleanField(default=True)),
                ('private_vehicle', models.BooleanField(default=True)),
                ('price_note', models.CharField(blank=True, help_text='Example: Starting from USD 45/day', max_length=150)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['display_order', '-is_featured', 'name'],
            },
        ),
    ]
