# Generated by Django 6.1.1 on 2026-09-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripbooking',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
