# Generated by Django 6.1.1 on 2026-09-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_tripbooking_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/gallery/')),
                ('photo_type', models.CharField(choices=[('front', 'Front View'), ('exterior', 'Exterior'), ('side', 'Side View'), ('rear', 'Rear View'), ('interior', 'Interior'), ('seats', 'Seats'), ('dashboard', 'Dashboard'), ('luggage', 'Luggage Space'), ('other', 'Other')], default='exterior', max_length=30)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.vehicle')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
