# Generated by Django 6.1.1 on 2026-09-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_vehiclephoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehiclePhoto',
        ),
    ]
